### ISSUE TITLE
Large datagram can block SendMessage and never be sent

### ISSUE THREAD

**Issue by tanghaowillow** [quic-go/quic-go#4003] opened 2023-07-29 15:46 UTC
Currently the check in SendMessage only requires the size of the datagram is not greater than peer's max_datagram_frame_size parameter. However some implementations send 65535 as max_datagram_frame_size  to indicate accepting any datagram frame, which makes SendMessage may put a large datagram frame to the send queue and the frame may never be sent if it is too large to fit in a packet. Maybe the size check in SendMessage can be more strict so that the case above can cause an error instead of blocking following calls to SendMessage?

**Comment by marten-seemann** [comment] 2023-07-30 17:18
Duplicate of #3222.

**Closed by marten-seemann** 2023-07-30 17:18 UTC
