### ISSUE TITLE
error undefined: qtls.*

### ISSUE THREAD

**Issue by ManuelReschke** [quic-go/quic-go#3933] opened 2023-06-30 13:12 UTC
go version
go version **go1.20.5 linux/amd64**

**if i want to build my project i get the following error. What can i do?**

github.com/quic-go/quic-go/internal/qtls
/home/manuel/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:18:15: undefined: qtls.Alert
/home/manuel/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:24:26: undefined: qtls.CipherSuiteTLS13
/home/manuel/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:36:25: undefined: qtls.ConnectionStateWith0RTT
/home/manuel/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:38:25: undefined: qtls.EncryptionLevel
/home/manuel/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:40:19: undefined: qtls.Extension
/home/manuel/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:44:21: undefined: qtls.RecordLayer
/home/manuel/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:49:29: undefined: qtls.EncryptionHandshake
/home/manuel/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:51:24: undefined: qtls.Encryption0RTT
/home/manuel/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:53:31: undefined: qtls.EncryptionApplication
/home/manuel/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:58:14: undefined: qtls.AEADAESGCMTLS13
/home/manuel/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:58:14: too many errors

**Comment by marten-seemann** [comment] 2023-06-30 15:53
Duplicate of #3907. Duplicate of #3927.

Really, please search through the issues first before opening the same one again and again and again.

**Closed by marten-seemann** 2023-06-30 15:53 UTC
