### ISSUE TITLE
How do I use the same client for both http2 and http3?

### ISSUE THREAD

**Issue by rew1nter** [quic-go/quic-go#4474] opened 2024-05-03 03:10 UTC
with quic-go requests time out when http2 servers are encountered. Is there a way to also make it work for http2 (and http1)?

**Comment by marten-seemann** [comment] 2024-05-03 23:20
Unfortunately not at the moment.

Duplicate of #4336 and #3772.

**Closed by marten-seemann** 2024-05-03 23:20 UTC
