### ISSUE TITLE
URL in HTTP/3 CONNECT request seems wrong.

### ISSUE THREAD

**Issue by Jerry0666** [quic-go/quic-go#3786] opened 2023-04-24 04:42 UTC
I am trying to do CONNECT request in http/3, I make the request use http.NewRequest, but when server receive the request, the URL seems wrong, and I can't use handler function to deal with it.
Here is the client code.
```
package main

import (
	"bytes"
	//"crypto/x509"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"

	"crypto/tls"

	"github.com/quic-go/quic-go"
	"github.com/quic-go/quic-go/http3"
)

func print_req(req *http.Request) {
	fmt.Println("req info:")
	fmt.Printf("Method: %s\n", req.Method)
	fmt.Println("URL:")
	fmt.Println(req.URL)
}

func main() {

	var qconf quic.Config

	//insecure := true
	f, err := os.OpenFile("/home/demo/sshkeylog.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
	if err != nil {
		panic(err)
	}
	//pool, err := x509.SystemCertPool()
	roundTripper := &http3.RoundTripper{
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
			KeyLogWriter:       f,
		},
		QuicConfig: &qconf,
	}

	hclient := &http.Client{
		Transport: roundTripper,
	}
	defer roundTripper.Close()
	addr := "https://127.0.0.1:9000/"
	rsp, err := hclient.Get(addr)

	if err != nil {
		log.Fatal(err)
	}

	body := &bytes.Buffer{}
	_, err = io.Copy(body, rsp.Body)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Response Body: %s\n", body.Bytes())

	req, err := http.NewRequest("CONNECT", "https://127.0.0.1:9000/ping", nil)
	if err != nil {
		fmt.Println("create request error")
		fmt.Println(err)
	}
	res, err := hclient.Do(req)

	if err != nil {
		fmt.Println("do req error")
		fmt.Println(err)
	}

	_, err = io.Copy(body, res.Body)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("rse body: %s\n", body.Bytes())

	req, err = http.NewRequest("GET", "https://127.0.0.1:9000/ping", nil)
	if err != nil {
		fmt.Println("create request error")
		fmt.Println(err)
	}
	res, err = hclient.Do(req)
	//print_req(req)
	if err != nil {
		fmt.Println("do req error")
		fmt.Println(err)
	}

	_, err = io.Copy(body, res.Body)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("rse body: %s\n", body.Bytes())

}
```
The server code.
```
package main

import (
	//"bytes"
	//"encoding/json"
	"fmt"
	//"io/ioutil"
	"net/http"

	"github.com/codegangsta/negroni"
	"github.com/quic-go/quic-go/http3"
)

type requestLogger struct{}

func (rl requestLogger) ServeHTTP(w http.ResponseWriter, r *http.Request) {

	fmt.Printf("method: %s\n", r.Method)
	fmt.Printf("URL: %s\n", r.URL)
	fmt.Printf("URI: %s\n", r.RequestURI)
	fmt.Println()
}

func main() {

	mux := http.NewServeMux()

	mux.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
		fmt.Fprintf(w, "Welcome to the home page!")
		fmt.Println("req info:")
		fmt.Printf("Method: %s\n", req.Method)
		fmt.Println("URL:")
		fmt.Println(req.URL)
	})

	n := negroni.New()
	n.Use(negroni.NewLogger())
	n.UseHandler(mux)

	// server := http3.Server{
	// 	Handler: n,
	// 	Addr:    "127.0.0.1:9000",
	// }
	//err := server.ListenAndServeTLS("cert.pem", "key.pem")
	err := http3.ListenAndServe("127.0.0.1:9000", "cert.pem", "key.pem", requestLogger{})
	if err != nil {
		fmt.Println("ListenAndServeTLS error")
		fmt.Println(err)
	}
}
```
The output of server.
```
method: GET
URL: /
URI: /

method: CONNECT
URL: //127.0.0.1:9000
URI: 127.0.0.1:9000

method: GET
URL: /ping
URI: /ping
```
Did I do wrong?And how to correct use CONNECT request?

**Comment by marten-seemann** [comment] 2023-04-25 21:22
I haven't had the time to run your code yet, but this doesn't look like you did something wrong. Probably the http3 package didn't properly re-assemble your request.

Want to debug and submit a fix?

**Comment by Glonee** [comment] 2023-05-02 03:05
This is not a bug, but a sepcial behaviour of CONNECT method:

https://github.com/golang/go/blob/04f059f9efbb2a202ddb6a3c6f87efa8073e562f/src/net/http/request.go#L1064-L1085
>CONNECT requests are used two different ways, and neither uses a full URL: The standard use is to tunnel HTTPS through an HTTP proxy. It looks like "CONNECT www.google.com:443 HTTP/1.1", and the parameter is just the authority section of a URL.

We shoud close this issue since there is nothing wrong.

**Comment by marten-seemann** [comment] 2023-06-21 11:20
Thank you @Glonee!

**Closed by marten-seemann** 2023-06-21 11:20 UTC
Labels: bug, help wanted, http3
