### ISSUE TITLE
quic-go  example echo.go run on Android error

### ISSUE THREAD

**Issue by lloovve** [quic-go/quic-go#4383] opened 2024-03-22 06:24 UTC
when i run echo.go  

**my device info：**

> persist.freeme.product.model]: [DATANG T32e]
> [ro.build.product]: [DATANG T32e]
> [ro.freeme.alter.product_model]: [1]
> [ro.product.board]: [DATANG T32e]
> [ro.product.brand]: [DATANG T32e]
> [ro.product.cpu.abi]: [armeabi-v7a]
> [ro.product.cpu.abi2]: [armeabi]
> [ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
> [ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
> [ro.product.cpu.abilist64]: []
> [ro.product.device]: [DATANG T32e]
> [ro.product.first_api_level]: [27]
> [ro.product.locale]: [zh-CN]
> [ro.product.manufacturer]: [DATANG T32e]
> [ro.product.model]: [DATANG T32e]
> [ro.product.name]: [DATANG T32e]
> [ro.vendor.product.brand]: [DATANG T32e]
> [ro.vendor.product.device]: [DATANG T32e]
> [ro.vendor.product.manufacturer]: [DATANG T32e]
> [ro.vendor.product.model]: [DATANG T32e]
> [ro.vendor.product.name]: [DATANG T32e]

`panic: INTERNAL_ERROR (local): write udp [::]:40867->127.0.0.1:4242: sendmsg: invalid argument`

**Comment by marten-seemann** [comment] 2024-03-22 06:28
Most likely a duplicate of https://github.com/quic-go/quic-go/issues/4178.

**Closed by marten-seemann** 2024-03-22 06:28 UTC

**Comment by lloovve** [comment] 2024-03-22 07:22
when i use quic in gomobile ，can not use export QUIC_GO_DISABLE_ECN=true to save this err ，any other way ？

**Comment by lloovve** [comment] 2024-03-22 07:23
> Most likely a duplicate of #4178.

when i use quic in gomobile ，can not use export QUIC_GO_DISABLE_ECN=true to save this err ，any other way ？
