### ISSUE TITLE
MaxIncomingStreams does not reflect closed streams

### ISSUE THREAD

**Issue by kokes** [quic-go/quic-go#3558] opened 2022-09-20 08:59 UTC
I've run into an issue possibly related to #2709 that I've been able to reproduce using the following gist, adapted from the gist linked in the issue. If I remove the reading/writing bits and just close the stream (from both sides), the MAX_STREAMS update doesn't seem to be communicated, I'm not able to create any new streams and it blocks.

In this edited gist I've removed the binary.{Read,Write} and just closed the stream from both sides and added a bit of logging. I set `MaxIncomingStreams` to 2 and after two initiated (and closed) streams... it just gets stuck.

https://gist.github.com/kokes/15324dce93a41fff61cbbf101bc45590

```
$ go run repro.go
10:03:16 repro2.go:42: TAP ENTER TO SEND THE NEXT NUMBER TO THE CLIENT

10:03:17 repro2.go:62: closed a stream from the server side
10:03:17 repro2.go:42: TAP ENTER TO SEND THE NEXT NUMBER TO THE CLIENT
10:03:17 repro2.go:94: closed a stream from the client side

10:03:17 repro2.go:62: closed a stream from the server side
10:03:17 repro2.go:42: TAP ENTER TO SEND THE NEXT NUMBER TO THE CLIENT
10:03:17 repro2.go:94: closed a stream from the client side

10:03:51 repro2.go:50: timeout: no recent network activity
exit status 1
```

Am I using it wrong or does the information not get through over the wire?

Thanks!

**Comment by marten-seemann** [comment] 2022-09-20 19:41
I don't have the time to debug your code, but you'll need to call `Close` (or reset the stream) from both sides.

**Comment by kokes** [comment] 2022-09-21 06:06
That's the idea, I explicitly close it from both sides, but upon further investigation, there are other issues at play.

I further simplified the code to just this (+ logging)

```go
// server goroutine
for {
    stream, err := session.OpenStreamSync(context.Background())
    if err != nil {
        log.Fatal(err)
    }

    if err := stream.Close(); err != nil {
        log.Printf("problem closing stream: %v", err)
    }
}
// client goroutine
for {
    stream, err := session.AcceptStream(context.Background())
    if err != nil {
        log.Fatalf("client (during AcceptStream): %v", err)
    }

    if err := stream.Close(); err != nil {
        log.Fatalf("a problem closing the stream from the client side: %v", err)
    }
}
```

And the odd thing is that no matter how much time I wait after opening that bidi stream... **the client only accepts it after it's closed by the server**, which could mess up the concurrent connection counter.

```
$ go run maxs.go
07:59:00 maxs.go:20: starting up
07:59:01 maxs.go:43: server: opened a stream: 1
07:59:02 maxs.go:50: server: closed a stream: 1
07:59:02 maxs.go:43: server: opened a stream: 5
07:59:02 maxs.go:76: client: accepted a stream: 1
07:59:02 maxs.go:81: client: closed a stream: 1
07:59:03 maxs.go:50: server: closed a stream: 5
07:59:03 maxs.go:76: client: accepted a stream: 5
07:59:03 maxs.go:81: client: closed a stream: 5
07:59:33 maxs.go:41: timeout: no recent network activity
```

However, if I add a `stream.Write([]byte{1,2,3})` to the server side after opening the bidi stream, it suddenly reorders to the way I'd expect (server open, client accept, client closes, server closes). And just like before - both sides close the stream yet AcceptStream blocks after two stream have come and gone.

```
$ go run maxs.go
08:04:17 maxs.go:20: starting up
08:04:18 maxs.go:43: server: opened a stream: 1
08:04:18 maxs.go:76: client: accepted a stream: 1
08:04:18 maxs.go:81: client: closed a stream: 1
08:04:19 maxs.go:50: server: closed a stream: 1
08:04:19 maxs.go:43: server: opened a stream: 5
08:04:19 maxs.go:76: client: accepted a stream: 5
08:04:19 maxs.go:81: client: closed a stream: 5
08:04:20 maxs.go:50: server: closed a stream: 5
08:04:50 maxs.go:74: client (during AcceptStream): timeout: no recent network activity
```

(Also the timeout is from the other side.)

**Comment by marten-seemann** [comment] 2022-09-21 06:10
That makes sense, opening a stream doesn’t send anything on the wire. Only when you write to the stream will your peer learn that you’ve opened a stream.

**Comment by kokes** [comment] 2022-09-21 06:20
But even in the first case (when no data got exchanged) did the peer learn that - when the server closed it. So proper accounting should lead to the fact that there were zero concurrent connections in the end. But that was not the case.

To close the loop: if I add writing to the server, it still doesn't help (as noted above), but if I drain the stream from the client side (`io.Copy(io.Discard, stream)`), it all starts working and the concurrent stream accounting kicks in and allows new streams to be created.

So it's not the existence of the stream that doesn't get communicated - we clearly see from the logs that both sides agree two streams - 1 and 5 - are in play. It's the server's `Close()` that's not understood by the client unless 1) servers sends some data, 2) client reads them all.

---

I'll dig into the code a bit if I have time, but it seems like the `Close` packet is at the end of some read queue on the client, which doesn't get read unless I read the data first.

**Comment by marten-seemann** [comment] 2022-09-21 07:12
Yes, you have to read the EOF, or alternatively reset the stream. If you don’t read the EOF, quic-go still has to keep the stream around, as might read from the stream later.

**Comment by kokes** [comment] 2022-09-21 07:29
I finally see where the confusion on my part comes from. The `Close()` method on the client side is to close the `io.Writer` as it's from the SendStream interface, **it does not close the stream itself**. Seems counterintuitive for a bidirectional stream to have a `Close()` method that only closes one side of the pipe... This feels like it's just `CancelWrite`. `Close()` should (in my opinion) call `CancelRead` and `CancelWrite` as the stream is closing down.

Anywho, CancelRead (with Close right after) on the client side does what I need - it closes the Stream properly and releases all resources tied to it, even if I didn't read until EOF.

**Comment by peterjeremy** [comment] 2022-10-09 05:21
I've just discovered this bug whilst investigating the cause of unexpected `too many open streams` errors.  The idiomatic Go approach is:
```
  f, err := foo.Open(...)
  if err != nil { return err }
  defer f.Close()
```

Streams are not well documented as is and requiring an additional `f.CancelRead(something)` is not at all obvious - especially since `CancelRead()` is documented as an "abort" operation, rather than a normal "close".  An additional wrinkle is that `CancelRead` requires a `StreamErrorCode` argument and there don't appear to be any such codes defined.  `NoError` seems an obvious choice but it is (non-obviously) a `TransportErrorCode`, rather than a `StreamErrorCode`.

In my case, I am reading all the data from the stream, but by knowing how many bytes to read, rather than reading to EOF - there's no indication that the latter behaviour is required.

As with @kokes, updating my code to `defer func() { f.CancelRead(0); f.Close() }()` seems to have worked around this bug.

**Comment by marten-seemann** [comment] 2024-12-29 08:02
Closing this issue, since there doesn't seem to be anything that needs to be resolved.

The non-obvious behavior called out here is now documented on quic-go.net.

**Closed by marten-seemann** 2024-12-29 08:02 UTC
