### ISSUE TITLE
v0.36.0 build fail with undefined structs and or funcs

### ISSUE THREAD

**Issue by ritoon** [quic-go/quic-go#3927] opened 2023-06-27 11:57 UTC
Hello I have the same issue with others versions v0.35.1 and v0.35.0 did you change the interface ?
```
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o app .
# github.com/quic-go/quic-go/internal/qtls
vendor/github.com/quic-go/quic-go/internal/qtls/go120.go:18:15: undefined: qtls.Alert
vendor/github.com/quic-go/quic-go/internal/qtls/go120.go:24:26: undefined: qtls.CipherSuiteTLS13
vendor/github.com/quic-go/quic-go/internal/qtls/go120.go:36:25: undefined: qtls.ConnectionStateWith0RTT
vendor/github.com/quic-go/quic-go/internal/qtls/go120.go:38:25: undefined: qtls.EncryptionLevel
vendor/github.com/quic-go/quic-go/internal/qtls/go120.go:40:19: undefined: qtls.Extension
vendor/github.com/quic-go/quic-go/internal/qtls/go120.go:44:21: undefined: qtls.RecordLayer
vendor/github.com/quic-go/quic-go/internal/qtls/go120.go:49:29: undefined: qtls.EncryptionHandshake
vendor/github.com/quic-go/quic-go/internal/qtls/go120.go:51:24: undefined: qtls.Encryption0RTT
vendor/github.com/quic-go/quic-go/internal/qtls/go120.go:53:31: undefined: qtls.EncryptionApplication
vendor/github.com/quic-go/quic-go/internal/qtls/go120.go:58:14: undefined: qtls.AEADAESGCMTLS13
vendor/github.com/quic-go/quic-go/internal/qtls/go120.go:58:14: too many errors
make[1]: *** [buildbin] Error 1
make: *** [push-dev] Error 2
```

**Comment by marten-seemann** [comment] 2023-06-27 15:19
Duplicate of #3907. Please make sure you don't upgrade qtls to a version that's higher than what's in v0.36.0's go.mod.

**Closed by marten-seemann** 2023-06-27 15:19 UTC
